### ISSUE TITLE
IpfixPacket::write: Maybe wrong calculated IPFIX lengths and FlowSet lengths for Set::Data

### ISSUE THREAD

**Issue by andreaz98** [NetGauze/NetGauze#360]
Hello, I made my experimentation on the latest main commit https://github.com/NetGauze/NetGauze/commit/3524e5d4999f94e71acbc98c0d096787ce3db17f.

In my application, I send 10 DataRecords over IPFIX to the local collector. The problem is both `Length` and `FlowSet Length` don't seem correct to me anywhere in [this pcap](https://gofile.io/d/84ttnW) (except the first packet i.e. the OptionsTemplate).

For instance, let's take a random packet from the pcap. We take packet number 10.
Length: 556 (0x22c) | `0x30 + 0x22c = 0x25c` (expected `0x26f` i.e. end of packet) where `0x30` is the beginning of the IPFIX packet.
FlowSet Length: 540 (0x21c) | `0x40 + 0x21c = 0x25c` (expected `0x26f` i.e. end of packet) where `0x40` is the beginning of the FlowSet.
You can notice `0x25c` is a byte (= `0x79` = `y`) that belongs to the last flow.

<img width="901" height="337" alt="Image" src="https://github.com/user-attachments/assets/e40fd51b-3058-4b48-9629-039b08a46fa6" />

In my specific case (but I can't share the pcap) what happens is that the `0x30 + Length` and `0x40 + FlowSet Length` byte overlap with a byte in the second-last flow and wireshark doesn't recognize the 10th flow.

Maybe I'm doing something wrong.

If you need something else I'm here.

**Comment by ahassany** [comment]
@andreaz98 that's indeed a different bug for padding calculation on parsing, it's very tricky with variable size fields. Unfortunately, IPFIX packet doesn't tell how many data records are in a Set, so the parser has to guess for each byte it's parsing if it's a data record or padding.

Should be fixed in #362 .

**Comment by andreaz98** [comment]
Hello @ahassany, sorry for the delay. I was on vacation.

> [@andreaz98](https://github.com/andreaz98) that's indeed a different bug for padding calculation on parsing, it's very tricky with variable size fields. Unfortunately, IPFIX packet doesn't tell how many data records are in a Set, so the parser has to guess for each byte it's parsing if it's a data record or padding.
> 
> Should be fixed in [#362](https://github.com/NetGauze/NetGauze/pull/362) .

I've just tested [#362](https://github.com/NetGauze/NetGauze/pull/362) and the problem is partially solved. Wireshark recognizes one padding byte as one Flow (there are 5 flows, wireshark counts 6 flows). So, the padding is still `0x00 0x00` but now the last flow is `0x00` instead of `0x00 0x00` as previously explained in https://github.com/NetGauze/NetGauze/issues/360#issuecomment-3685823150.

If you need anything else let me know.

**Comment by ahassany** [comment]
Hmm, guess I'm not able to get the optinal padding right. Anyways, padding is optional according to RFC7011 and for a software implementation it doesn't make sense to use as much as a hardware implementation.

I updated #370  and removed. the padding calculation all together. I need to redo the description of the PR in a later time.

I've used this small producer to reproduce the reported issue, and after the fix, it seems that wireshark reads the packets correctly.

```rust
use chrono::{TimeZone, Utc};
use futures_util::SinkExt;
use netgauze_flow_pkt::codec::FlowInfoCodec;
use netgauze_flow_pkt::ipfix::{
    DataRecord, DecodingTemplate, IpfixPacket, OptionsTemplateRecord, Set, TemplateRecord,
};
use netgauze_flow_pkt::{DataSetId, FieldSpecifier, ie};
use std::collections::HashMap;
use std::net::{Ipv4Addr, SocketAddr};
use std::str::FromStr;
use tokio_util::codec::Encoder;
use tokio_util::udp::UdpFramed;

/// Produce IPFIX packets to a UDP socket
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync + 'static>> {
    let socket = tokio::net::UdpSocket::bind("0.0.0.0:0").await?;
    let addr = SocketAddr::from_str("127.0.0.1:9991").expect("invalid address");
    let mut framed = UdpFramed::new(socket, FlowInfoCodec::default());

    let template_fixed_size = IpfixPacket::new(
        Utc.with_ymd_and_hms(2025, 12, 22, 11, 24, 7).unwrap(),
        1,
        12345,
        Box::new([Set::OptionsTemplate(Box::new([
            OptionsTemplateRecord::new(
                500,
                Box::new([
                    FieldSpecifier::new(ie::IE::VMWare(ie::vmware::IE::sessionFlags), 1).unwrap(),
                ]),
                Box::new([FieldSpecifier::new(
                    ie::IE::VMWare(ie::vmware::IE::virtualObsID),
                    u16::MAX,
                )
                .unwrap()]),
            ),
        ]))]),
    );

    let data_fixed = IpfixPacket::new(
        Utc.with_ymd_and_hms(2025, 12, 22, 11, 24, 8).unwrap(),
        2,
        12345,
        Box::new([Set::Data {
            id: DataSetId::new(500).unwrap(),
            records: Box::new([
                DataRecord::new(
                    Box::new([ie::Field::VMWare(ie::vmware::Field::sessionFlags(0x01))]),
                    Box::new([ie::Field::VMWare(ie::vmware::Field::virtualObsID(
                        "first text".into(),
                    ))]),
                ),
                DataRecord::new(
                    Box::new([ie::Field::VMWare(ie::vmware::Field::sessionFlags(0x02))]),
                    Box::new([ie::Field::VMWare(ie::vmware::Field::virtualObsID(
                        "second text".into(),
                    ))]),
                ),
                DataRecord::new(
                    Box::new([ie::Field::VMWare(ie::vmware::Field::sessionFlags(0x03))]),
                    Box::new([ie::Field::VMWare(ie::vmware::Field::virtualObsID(
                        "third text".into(),
                    ))]),
                ),
                DataRecord::new(
                    Box::new([ie::Field::VMWare(ie::vmware::Field::sessionFlags(0x04))]),
                    Box::new([ie::Field::VMWare(ie::vmware::Field::virtualObsID(
                        "fourth text".into(),
                    ))]),
                ),
                DataRecord::new(
                    Box::new([ie::Field::VMWare(ie::vmware::Field::sessionFlags(0x05))]),
                    Box::new([ie::Field::VMWare(ie::vmware::Field::virtualObsID(
                        "fifth text".into(),
                    ))]),
                ),
                DataRecord::new(
                    Box::new([ie::Field::VMWare(ie::vmware::Field::sessionFlags(0x06))]),
                    Box::new([ie::Field::VMWare(ie::vmware::Field::virtualObsID(
                        "sixth text".into(),
                    ))]),
                ),
            ]),
        }]),
    );

    framed.send((template_fixed_size.clone(), addr)).await?;
    framed.send((data_fixed.clone(), addr)).await?;

    Ok(())
}
```
